### ISSUE TITLE
Question: deepLink like IOS sdk

### ISSUE THREAD

**Issue by fishkingsin** [fujifilmssd/Android-Fujifilm-SPA-SDK-SampleApp#1]
as title 
https://github.com/fujifilmssd/iOS-Fujifilm-SPA-SDK-SampleApp/issues/4

**Comment by Jonathan-Nick** [comment]
Android and iOS deepLink values are structured the same way. 

Example:
            Map<String, Serializable> extraOptions = new HashMap<>();
            extraOptions.put(FujifilmSPA.EXTRA_LAUNCH_LINK, "walmart");
